apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: xdeployments.example.org
spec:
  group: example.org
  names:
    kind: XDeployment
    plural: xdeployments
  scope: Namespaced
  versions:
  - name: v1
    referenceable: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              env:
                items:
                  properties:
                    name:
                      type: string
                    value:
                      type: string
                  type: object
                type: array
              hostname:
                type: string
              image:
                type: string
              port:
                type: integer
            required:
            - image
            type: object
          status:
            properties:
              address:
                type: string
              replicas:
                type: integer
            type: object
        type: object
    served: true

